In [43]:
import pandas as pd
import numpy as np
from os import path

In [22]:
raw_files='/Users/liualg/Documents/GitHub/SeroNet/outbreak/_output-fast'
new_york=pd.read_csv(path.join(raw_files,'New York_data-pangoterms.csv'))
arizona=pd.read_csv(path.join(raw_files,'Arizona_data-pangoterms.csv'))
minnesota=pd.read_csv(path.join(raw_files,'Minnesota_data-pangoterms.csv'))

In [60]:
ny_subset = new_york[(new_york['date'] >= '2020-08-01') & 
         (new_york['date'] < '2021-05-01') &
         (new_york['prevalence'] > 0)
        ]

az_subset = arizona[(arizona['date'] >= '2020-08-01') & 
         (arizona['date'] < '2021-05-01') &
         (arizona['prevalence'] > 0)
        ]

mn_subset = minnesota[(minnesota['date'] >= '2020-08-01') & 
         (minnesota['date'] < '2021-05-01') &
         (minnesota['prevalence'] > 0)
        ]

total = list(ny_subset['term']) + list(az_subset['term']) + list(mn_subset['term']) 
set(total)

{'Alpha',
 'B.1.1.318-related',
 'B.1.617.3',
 'Beta',
 'C.36.3-related',
 'Delta',
 'Epsilon',
 'Eta',
 'Gamma',
 'Iota',
 'Kappa',
 'Lambda',
 'Mu',
 'Omicron',
 'Zeta',
 nan}

In [64]:
set(mn_subset['term'])

{'Alpha',
 'B.1.1.318-related',
 'Beta',
 'C.36.3-related',
 'Delta',
 'Epsilon',
 'Eta',
 'Gamma',
 'Iota',
 'Kappa',
 'Lambda',
 'Mu',
 'Omicron',
 'Zeta',
 nan}

In [61]:
ny_subset.tail()

,date,total_count,lineage_count,lineage,prevalence,prevalence_rolling,term
31667,2021-04-30,263,3,c.37,0.011407,0.003965,Lambda
31670,2021-04-30,263,12,p.1,0.045627,0.040215,Gamma
31671,2021-04-30,263,3,p.1.10,0.011407,0.007363,Gamma
31677,2021-04-30,263,1,q.3,0.003802,0.002266,Alpha
31679,2021-04-30,263,2,r.1,0.007605,0.004531,NaN

In [58]:
ny_subset_l = new_york[(new_york['date'] >= '2020-08-01') & 
         (new_york['date'] < '2021-05-01') &
         (new_york['prevalence'] > 0) &
        (new_york['term'].isna())
        ]

az_subset_l = arizona[(arizona['date'] >= '2020-08-01') & 
         (arizona['date'] < '2021-05-01') &
         (arizona['prevalence'] > 0) &
        (arizona['term'].isna())
        
        ]

mn_subset_l = minnesota[(minnesota['date'] >= '2020-08-01') & 
         (minnesota['date'] < '2021-05-01') &
         (minnesota['prevalence'] > 0) &
        (minnesota['term'].isna())
        ]

total = list(ny_subset_l['lineage']) + list(az_subset_l['lineage']) + list(mn_subset_l['lineage']) 
set(total)

{'a',
 'a.1',
 'a.19',
 'a.2',
 'a.2.5',
 'a.2.5.1',
 'a.2.5.2',
 'a.2.5.3',
 'a.21',
 'a.23.1',
 'a.27',
 'a.28',
 'b',
 'b.1',
 'b.1.1',
 'b.1.1.1',
 'b.1.1.10',
 'b.1.1.101',
 'b.1.1.116',
 'b.1.1.117',
 'b.1.1.118',
 'b.1.1.128',
 'b.1.1.135',
 'b.1.1.141',
 'b.1.1.148',
 'b.1.1.159',
 'b.1.1.161',
 'b.1.1.164',
 'b.1.1.168',
 'b.1.1.177',
 'b.1.1.186',
 'b.1.1.189',
 'b.1.1.192',
 'b.1.1.205',
 'b.1.1.207',
 'b.1.1.216',
 'b.1.1.222',
 'b.1.1.225',
 'b.1.1.226',
 'b.1.1.228',
 'b.1.1.231',
 'b.1.1.243',
 'b.1.1.244',
 'b.1.1.25',
 'b.1.1.251',
 'b.1.1.258',
 'b.1.1.265',
 'b.1.1.27',
 'b.1.1.28',
 'b.1.1.285',
 'b.1.1.291',
 'b.1.1.294',
 'b.1.1.304',
 'b.1.1.305',
 'b.1.1.306',
 'b.1.1.315',
 'b.1.1.316',
 'b.1.1.317',
 'b.1.1.322',
 'b.1.1.325',
 'b.1.1.328',
 'b.1.1.329',
 'b.1.1.33',
 'b.1.1.331',
 'b.1.1.334',
 'b.1.1.337',
 'b.1.1.344',
 'b.1.1.345',
 'b.1.1.347',
 'b.1.1.348',
 'b.1.1.351',
 'b.1.1.352',
 'b.1.1.354',
 'b.1.1.357',
 'b.1.1.359',
 'b.1.1.362',
 'b.1.1.368',
 'b.1.1.372',
 'b.1.1.376',
 'b.1.1.381',
 'b.1.1.389',
 'b.1.1.39',
 'b.1.1.392',
 'b.1.1.397',
 'b.1.1.403',
 'b.1.1.404',
 'b.1.1.411',
 'b.1.1.416',
 'b.1.1.420',
 'b.1.1.432',
 'b.1.1.434',
 'b.1.1.437',
 'b.1.1.441',
 'b.1.1.453',
 'b.1.1.46',
 'b.1.1.461',
 'b.1.1.462',
 'b.1.1.464',
 'b.1.1.467',
 'b.1.1.480',
 'b.1.1.482',
 'b.1.1.486',
 'b.1.1.50',
 'b.1.1.515',
 'b.1.1.517',
 'b.1.1.518',
 'b.1.1.519',
 'b.1.1.523',
 'b.1.1.525',
 'b.1.1.526',
 'b.1.1.59',
 'b.1.1.70',
 'b.1.1.71',
 'b.1.1.72',
 'b.1.1.75',
 'b.1.1.8',
 'b.1.108',
 'b.1.110.3',
 'b.1.111',
 'b.1.115',
 'b.1.126',
 'b.1.139',
 'b.1.147',
 'b.1.160',
 'b.1.160.23',
 'b.1.164',
 'b.1.177',
 'b.1.177.46',
 'b.1.177.53',
 'b.1.177.54',
 'b.1.177.86',
 'b.1.188',
 'b.1.189',
 'b.1.192',
 'b.1.195',
 'b.1.199',
 'b.1.2',
 'b.1.206',
 'b.1.210',
 'b.1.214.2',
 'b.1.214.3',
 'b.1.221',
 'b.1.229',
 'b.1.232',
 'b.1.233',
 'b.1.234',
 'b.1.236',
 'b.1.239',
 'b.1.240',
 'b.1.241',
 'b.1.243',
 'b.1.243.1',
 'b.1.258',
 'b.1.258.5',
 'b.1.263',
 'b.1.265',
 'b.1.280',
 'b.1.289',
 'b.1.293',
 'b.1.294',
 'b.1.298',
 'b.1.3',
 'b.1.301',
 'b.1.302',
 'b.1.304',
 'b.1.305',
 'b.1.306',
 'b.1.308',
 'b.1.309',
 'b.1.311',
 'b.1.313',
 'b.1.315',
 'b.1.318',
 'b.1.319',
 'b.1.320',
 'b.1.323',
 'b.1.324',
 'b.1.334',
 'b.1.336',
 'b.1.337',
 'b.1.340',
 'b.1.343',
 'b.1.346',
 'b.1.349',
 'b.1.350',
 'b.1.357',
 'b.1.36',
 'b.1.36.1',
 'b.1.36.18',
 'b.1.36.24',
 'b.1.36.29',
 'b.1.36.31',
 'b.1.36.34',
 'b.1.36.35',
 'b.1.36.38',
 'b.1.36.8',
 'b.1.360',
 'b.1.361',
 'b.1.362',
 'b.1.363',
 'b.1.369',
 'b.1.371',
 'b.1.375',
 'b.1.377',
 'b.1.382',
 'b.1.385',
 'b.1.390',
 'b.1.395',
 'b.1.396',
 'b.1.397',
 'b.1.398',
 'b.1.399',
 'b.1.400',
 'b.1.400.1',
 'b.1.401',
 'b.1.402',
 'b.1.403',
 'b.1.404',
 'b.1.405',
 'b.1.409',
 'b.1.413',
 'b.1.420',
 'b.1.421',
 'b.1.423',
 'b.1.424',
 'b.1.425',
 'b.1.426',
 'b.1.433',
 'b.1.436',
 'b.1.437',
 'b.1.438.4',
 'b.1.443',
 'b.1.448',
 'b.1.451',
 'b.1.452',
 'b.1.453',
 'b.1.466.2',
 'b.1.471',
 'b.1.478',
 'b.1.479',
 'b.1.480',
 'b.1.489',
 'b.1.499',
 'b.1.499.1',
 'b.1.503',
 'b.1.506',
 'b.1.507',
 'b.1.509',
 'b.1.516',
 'b.1.517',
 'b.1.517.1',
 'b.1.521',
 'b.1.523',
 'b.1.527',
 'b.1.530',
 'b.1.533',
 'b.1.539',
 'b.1.541',
 'b.1.543',
 'b.1.544',
 'b.1.550',
 'b.1.551',
 'b.1.556',
 'b.1.558',
 'b.1.560',
 'b.1.561',
 'b.1.563',
 'b.1.564',
 'b.1.565',
 'b.1.567',
 'b.1.568',
 'b.1.569',
 'b.1.570',
 'b.1.572',
 'b.1.574',
 'b.1.575',
 'b.1.575.1',
 'b.1.576',
 'b.1.577',
 'b.1.578',
 'b.1.580',
 'b.1.581',
 'b.1.582',
 'b.1.585',
 'b.1.587',
 'b.1.588',
 'b.1.590',
 'b.1.591',
 'b.1.593',
 'b.1.595',
 'b.1.595.1',
 'b.1.595.2',
 'b.1.595.3',
 'b.1.595.4',
 'b.1.596',
 'b.1.599',
 'b.1.601',
 'b.1.602',
 'b.1.603',
 'b.1.604',
 'b.1.605',
 'b.1.606',
 'b.1.609',
 'b.1.612',
 'b.1.617',
 'b.1.619',
 'b.1.620',
 'b.1.623',
 'b.1.625',
 'b.1.627',
 'b.1.631',
 'b.1.634',
 'b.1.635',
 'b.1.636',
 'b.1.637',
 'b.1.639',
 'b.12',
 'b.23',
 'b.28',
 'b.33',
 'b.45',
 'b.50',
 'b.59',
 'c.1',
 'c.13',
 'c.16',
 'c.17',
 'c.2.1',
 'c.23',
 'c.28',
 'c.31',
 'c.35',
 'c.36',
 'c.38',
 'l.3',
 'n.5',
 'r.1',
 'r.2',
 'w.1',
 'xb'}

In [59]:
ny_subset_l

,date,total_count,lineage_count,lineage,prevalence,prevalence_rolling,term
5587,2020-08-01,10,2,b.1,0.200000,0.157480,NaN
5588,2020-08-01,10,1,b.1.1,0.100000,0.078740,NaN
5592,2020-08-01,10,1,b.1.1.231,0.100000,0.039370,NaN
5604,2020-08-01,10,1,b.1.2,0.100000,0.118110,NaN
5611,2020-08-01,10,1,b.1.306,0.100000,0.039370,NaN
...,...,...,...,...,...,...,...
31640,2021-04-30,263,1,b.1.2,0.003802,0.003398,NaN
31641,2021-04-30,263,1,b.1.243,0.003802,0.002266,NaN
31651,2021-04-30,263,2,b.1.575,0.007605,0.003398,NaN
31660,2021-04-30,263,25,b.1.637,0.095057,0.062872,NaN
31679,2021-04-30,263,2,r.1,0.007605,0.004531,NaN